trigger:
- main
variables:
  imageName: springbootapp
  tag: $(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:

# 1️⃣ Build Spring Boot JAR
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false

# 2️⃣ Build Docker Image (ONLY BUILD, no push)
- task: Docker@2
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: $(imageName)
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

# 2.5️⃣ Install Trivy
- script: |
    sudo apt-get update
    sudo apt-get install -y wget apt-transport-https gnupg lsb-release
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
    sudo apt-get update
    sudo apt-get install -y trivy
    trivy --version
  displayName: Install Trivy

# 2.6️⃣ Scan Local Docker Image BEFORE PUSH
- script: |
    trivy image --severity HIGH,CRITICAL --exit-code 1 --no-progress $(imageName):$(tag)
  displayName: Scan Docker Image

# 3️⃣ Push Docker Image to ACR (only if scan passes)
- task: Docker@2
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: $(imageName)
    command: 'push'
    tags: |
      $(tag)

  
 # 3️⃣ Deploy to AKS
- task: KubernetesManifest@1
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS-CONNECTION-NEW-2026'  # Your AKS service connection
    manifests: |
      aks-deploy-from-acr.yaml
    containers: |
      myaksacr98765.azurecr.io/springbootapp:$(Build.BuildId)
    arguments: '--validate=false'
    
